### ISSUE TITLE
Cannot open file 'res://Worlds/Node2D.tscn'

### ISSUE THREAD

**Issue by JupiterRider** [Libre-TrainSim/Libre-TrainSim#1]
Game crashes when pressing "Play" with following error:

```
E 0:00:13.210   load_interactive: Cannot open file 'res://Worlds/Node2D.tscn'.
  <C++ Error>   Condition "err != OK" is true. Returned: Ref<ResourceInteractiveLoader>()
  <C++ Source>  scene/resources/resource_format_text.cpp:1228 @ load_interactive()
  <Stack Trace> MainMenu.gd:105 @ _on_ItemList_itemTracks_selected()
```

**Comment by Jean28518** [comment]
Because Node2D.tscn is just a deprecated file. To test it out you have to duplictae "World-Pattern.tscn" and move it to res://Worlds/
But this is all highly Work In Progress, I am changing a lot at the time how a world is being loaded, because of the scenario feature. 
So maybe it would be better to wait a bit, until i am finished with the basics, on whose we can build up together :)
