### ISSUE TITLE
Use inheritance instead of specific scripting nodes

### ISSUE THREAD

**Issue by HaSa1002** [Libre-TrainSim/Libre-TrainSim#104]
Currently, behaviour is implemented using a general class (World, Train, Signal, ...) and a new `SpecificScripting` node. To align the code more with Godot's design philosophy, we should instead inherit that scripts and may even implement some callbacks

**Comment by Jean28518** [comment]
Thanks!
For me this issue is not relevant enough at the moment. 

But feel free to do a pull request!

(The most worlds don't use any specific scripting)
Specific scripting for trains and signals is important

**Comment by DasCapschen** [comment]
I'm also not sure if inheritance is necessary.

For signals:
They can be refactored (I've done this on my refactor branch) so that Signal.gd does all logic and emits signals, and the visual instances specific scripting reacts to those with only visual changes.
Imo this is fine and aligns with godots vision.

Something similar will work for trains

**Comment by HaSa1002** [comment]
A lot has happend since I opend the issue. I think the structure philosophy has changed and a good amount of refactors brought this closer to reality. There is no point in keeping this issue open
