### ISSUE TITLE
Distance is actually an offset

### ISSUE THREAD

**Issue by HaSa1002** [Libre-TrainSim/Libre-TrainSim#222]
The parameter "Distance" shown in the image below is not a distance, but rather an offset.
![grafik](https://user-images.githubusercontent.com/14185889/140588457-86e75b68-517d-4dab-9be6-f7f8a4bace69.png)

**Comment by DasCapschen** [comment]
Well yes, it is the distance along the rail.
Perhaps we could rename it to `Distance along Rail` or something.

And it is an offset in meters, not in %, so I think calling it distance is ok.

**Comment by HaSa1002** [comment]
Well IMHO it is an offset from the starting point. A distance is perpendicular to the rail

**Comment by DasCapschen** [comment]
Well an offset can really be anything, offset really just means `distance relative to something`. 
Like a parallel rail will have an offset of 20 meters from the original one, yet that would be perpendicular.

I think it is fine to leave it as is. I doubt anyone would be surprised that distance moved the signal *along* the rail, rather than perpendicular to it.

**Comment by Jean28518** [comment]
I will change this! Good point :)
