### ISSUE TITLE
Cannot load nor edit custom maps, because paths are hardcoded to res or not changed if they are not loaded as PCK

### ISSUE THREAD

**Issue by HaSa1002** [Libre-TrainSim/Libre-TrainSim#224]
You cannot load a map, because the paths in content.tres are hardcoded to `res` which is fine for PCKs and loaded mods, but will never work for files that are writable and reside for example in `user://editor`. LTS should detect whether or not the mod files are writeable and rewrite the file paths accordingly.

**Comment by DasCapschen** [comment]
content.tres should not even be considered for non-pck things.
The loading code works like:
- find .pck files
- find a content.tres next to the pck file
- load the content.tres and do some checks
- load the pck file

If you have loose files flying about in `user://`, then those should be ignored by content.tres and just be treated like normal files, like before.

Talk to me about this in Discord when you have time, because I feel like I'm not properly understanding this, just show me 😅
