### ISSUE TITLE
apply_scenario_to_signals fails because dictionaries are null

### ISSUE THREAD

**Issue by HaSa1002** [Libre-TrainSim/Libre-TrainSim#244]
World.gd:543:
```gdscript
func apply_scenario_to_signals(signals: Dictionary) -> void:
	## Apply Scenario Data
	for signalN in $Signals.get_children():
		if signals.has(signalN.name):
			signalN.set_scenario_data(signals[signalN.name]) # set_scenario_data wants to have dict, but may get null
```
Workaround, but probably not a fix:
```gdscript
func apply_scenario_to_signals(signals: Dictionary) -> void:
	## Apply Scenario Data
	for signalN in $Signals.get_children():
		if signals.has(signalN.name):
			signalN.set_scenario_data(signals[signalN.name] if signals[signalN.name] != null else {})
```

**Comment by DasCapschen** [comment]
I think what you did is fine. The scenarios.cfg saves null instead of empty dicts. This has always worked before (I think) and only broke because of the type hints. So doing {} if null is fine imo.

Or we just make sure that scenarios.cfg never contains any nulls. But they are written through a ConfigFile using a generic "set_value" function. I don't think this is feasible.
