### ISSUE TITLE
Some textures are transparent in the Godot editor

### ISSUE THREAD

**Issue by Miksimus1** [Libre-TrainSim/Libre-TrainSim#327]
On the GoDot engine, some textures are transparent (like rails or grass)
![Screenshot_20220131_171705](https://user-images.githubusercontent.com/98762775/151855875-245cada3-7eed-481a-8499-e15e72a829e1.png)

**Comment by HaSa1002** [comment]
Hey @Miksimus1,
This is because the 0.8 way of route creation doesn't work anymore in 0.9. You have to use the built-in track editor. Your plane image background doesn't work with the built-in editor out of the box. Is this a new map? If so, then please create a new map in the track editor, put the image on the ground/as the ground texture using the Godot editor and then edit it in-game.

**Comment by Miksimus1** [comment]
OK Thanks !

**Comment by HaSa1002** [comment]
If you need more help, feel free to ask here or over on Discord.
