### ISSUE TITLE
Red train with Easy mode off doesn't accelerate after braking

### ISSUE THREAD

**Issue by talmanau** [Libre-TrainSim/Libre-TrainSim#369]
If accelerator switch is in any position other than off, then after braking the accelerator doesn't work until after it is brought back to the off position.

**Comment by HaSa1002** [comment]
The behaviour you describe is actually wanted behaviour by the implementation. However, I feel like we should revisit the advanced driving mode as the feedback here is not clear. This will get even worse with controllers when we promote them to be more than a silent feature.

Going forward we need to decide how to handle this case. Either we say, we do want to have the current behaviour, but introduce snapping of the stick in order to avoid getting stuck in meaningless microstates or we could take a path similiar to derail valley by allowing both breaking and acceleration and thus creating a horrible mess that damages your train (at least makes squieky noise). Another option would be to delegate the exact behaviour to the trains themselves. Trains would benefit from the control as they can provide train specific feedback for such invalid input. However, I am not sure we really wanna delegate the validation to the trains.

What do you think @DasCapschen and everyone being interested?

**Comment by talmanau** [comment]
I am not a train expert but I thought that the brake was a separate system like in the car where you can still tap the brake while accelerating. I did some research and understand now that makes no sense in the context of train dynamic brakes, but believe electric trains make use of a combination of dynamic and physical brakes. I leave it up to those more knowledgeable to work this out.

**Comment by DasCapschen** [comment]
Sorry, I seem to have comepletely missed this...

I think we should stay true to reality, we are a train *simulator* after all 😉 
As far as I know, in reality there are 4 types of brakes:
- the train brake aka. indirect brake
  - brakes the entire train using air pressure
  - brakes automatically if pressure drops
  - used for stopping
  - causes most wear on the train, try not to use it
  - usually coupled with the electric brake (if ther is one, afaik)
  - **causes accelerator to not work unless put back into off position first**
- an independent aka. direct brake
  - brakes only the loco, using air
  - usually used only for shunting or parking
  - can cause derailment if applied too hard
  - **seems not to affect the accelerator, maybe?**
- a dynamic / electric brake
  - acts like an engine-brake / retarder in trucks
  - use it as much as you can
  - more efficient the faster you go ; useless at low speeds
  - brakes anything with an engine in it (usually just the loco)
  - used for speed control on slopes, not for stopping
  - can cause derailment if applied too hard
  - **causes accelerator to not work unless put back into off position first**
- spring applied brakes
  - essentially what a handbrake is in a car
  - used only for parking
  - **does not affect the accelerator**

In modern electric trains, if you have a combined accelerator/brake lever, like the Talent 2 for example, it would use electric brakes first, and below a certain speed the train air brake would kick in.

Right now, we really only simulate train / electric brakes, so this should cause the accelerator to behave in this way.  
I just checked, and at least in v0.9, there is a hint that tells the player to reset the accelerator if they get stuck like this 😄 

I'm not sure if all trains have this behaviour, but at least German ones do. It's called "Nullstellungszwang".

Sources:
- https://forums.dovetailgames.com/threads/train-brakes-vs-dynamic-braking.22184/
- https://www.reddit.com/r/trainsimworld/comments/iu95z8/what_should_i_use_more_for_breaking/
- https://steamcommunity.com/app/24010/discussions/14/617328415065763729/
- https://tflearn.weebly.com/bremse.html
- Train Sim World 2

**Comment by Jean28518** [comment]
It is documented when you press 'F2'.
