### ISSUE TITLE
jSettings crashes when unique nodes are not found

### ISSUE THREAD

**Issue by DasCapschen** [Libre-TrainSim/Libre-TrainSim#384]
### Summary
The FPS-Limiter PR #380 added functions `show_fps_limit` and `show_fps_limit_selector` in jSettings, which use unique node names `$"%LabelFpsLimitToggle"`.  

On first run, jSettings sets the default settings, also calling `set_vsync`, which in turn calls `show_fps_limit`, which in turn tries to get the unique node, but: the unique node does not exists when the main menu loads, because the settings scene is not loaded.

Please don't update UI from `set_` functions, instead you could update it from the `_on_Vsync_pressed` function.

**Comment by DasCapschen** [comment]
Nevermind, this was an issue on my side... accidentally used the wrong Godot version ... works fine with 3.5 🙈

**Comment by nalquas** [comment]
It doesn't crash for me. Could you provide detailed steps on how to reproduce the issue?

> the unique node does not exists when the main menu loads, because the settings scene is not loaded.

Shouldn't the settings scene always be loaded since it's being loaded via Godot's AutoLoad?

> Please don't update UI from `set_` functions, instead you could update it from the `_on_Vsync_pressed` function.

Sure, I can move some code around. The reason I wanted `set_vsync` to update the GUI was to initialize the GUI with the correct states according to current settings, but in retrospect initializing that in `update_settings_window` (which is called from `popup`) and doing the updates in `_on_whatever` should suffice.

**Comment by nalquas** [comment]
> Nevermind, this was an issue on my side... accidentally used the wrong Godot version ... works fine with 3.5 see_no_evil

Oh, okay then. Didn't see your new comment when typing the previous one
