### ISSUE TITLE
Full screen error

### ISSUE THREAD

**Issue by langonginc** [Libre-TrainSim/Libre-TrainSim#445]
### Summary

- The full screen exit when **I click "Play" in any track any train**.
- When I made it fullscreen on macOS, there was a black area (not a real window) on my Home Screen.

<img width="966" alt="image" src="https://user-images.githubusercontent.com/59787082/206328757-10f73980-3e83-48a1-8d0e-c3e4baada14e.png">

<img width="873" alt="image" src="https://user-images.githubusercontent.com/59787082/206329059-45691e98-4f37-4cee-83ee-a849f92c6690.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59787082/206329647-05fa73c7-9f5a-49f3-a489-6ad29e687419.png">

### How to reproduce

1. Click "Start" and select any track any train and click button "Play".
2. Wait the software load...
3. Full screen exit automatically.
4. Make it fullscreen again, the black area leave on the DESKTOP.

### Version
 - Game Version: 0.8
 - OS: macOS (Apple silicon M2) version Ventura 13.0.1

**Comment by langonginc** [comment]
By the way, is there any third-partied track or train to load?

**Comment by HaSa1002** [comment]
I have no idea what the issue is. There is anyone in the dev team owning a macOS device to my knowledge. Maybe this issue is fixed by accident in the new release (which is that close 👉 👈 ).
And no, so far nobody made a custom map. Again, the next version should make it whole lot easier so maybe, there is hope :)
I added the issue to the 0.9 release to recheck this issue after release.

**Comment by langonginc** [comment]
@HaSa1002 

Thanks for your help! I found that it was working properly in 0.0.9-beta1.
