### ISSUE TITLE
Windowsで全然インストール出来ん。どうにかしてくれ。

### ISSUE THREAD

**Issue by iskdjfjdjakdkfkksjhjdjs** [Libre-TrainSim/Libre-TrainSim#472]
Windowsで全然インストール出来ん。

**Comment by nalquas** [comment]
Hi, when writing issues in this repository, please use English so people understand what you want.

According to Google Translate, you wrote: "I can't install anything on Windows. do something about it"

Could you please give more details as to what exactly went wrong? Error messages, screenshots, game version, OS version, anything that seems relevant? Otherwise, we don't have anything to go on and can't solve the issue. Thanks.

**Comment by nalquas** [comment]
Closing due to lack of info.
