### ISSUE TITLE
Remove the maximum speed marker

### ISSUE THREAD

**Issue by TrojanerHD** [Libre-TrainSim/Libre-TrainSim#531]
### Summary

For more realism, I'd like to either have a toggleable option in the difficulty section of the settings to disable the red maximum speed marker that looks LZB-like in the train's HUD or just have it deleted entirely.

### Additional information

![image](https://github.com/Libre-TrainSim/Libre-TrainSim/assets/32276754/58396820-cb5a-488c-9943-924d0456c5e8)
(Screenshot taken on current master branch at [`3952171`](https://github.com/Libre-TrainSim/Libre-TrainSim/tree/3952171a8222b2f1f2a48b16adf946769ac1ae35))

**Comment by DasCapschen** [comment]
I would not be sad about outright deleting it, we do have other UI elements that indicate the maximum speed. Also you're right, it does look LZB like.  

Instead of deleting it, we could also just hide it behind the easy mode option, since easy mode does not use PZB etc.  
Then again, if it's just in easy mode, why not just delete it outright?

What do you say, @HaSa1002 @nalquas ?

**Comment by HaSa1002** [comment]
No hard feelings. I feel like it's nice to visually see the speed limit in the cab but that may be not so super important. Remember a number c'mon xD

**Comment by TrojanerHD** [comment]
> Remember a number c'mon xD

Let me introduce you to [Lf 2](https://www.fahrdienstleiter.net/fdl/signalbuch-langsamfahrsignale-lf#viewer-96dpd) and [Hp 2](https://en.wikipedia.org/wiki/Railway_signals_in_Germany#Main_signal/distant_signal_(H/V)_system), for example :P

**Comment by DasCapschen** [comment]
I think he means the other numbers in the UI that dispay the max speed :)  
(like in the top right corner)
