### ISSUE TITLE
Support jumping to stations and resetting scenario

### ISSUE THREAD

**Issue by Mrxx99** [Libre-TrainSim/Libre-TrainSim#74]
It would be great if it was possible to jump to stations during the game via a menu (like in OpenBVE) and to reset/restart the scenario. Jumping to a station should not change the time, but resetting should (it could just reload the scenario).

*Edited by developer:*
## To Do:
- [x] Implement automatic GUI which finds every possible station, display a warning that the scenario experience specially with other trains couldn't be the best, and that feature is experimental
- [x] The time should be switched. Every signal could optionally change it's state with in this time jump.
- [x] All npcs between the player and the destination jump station should be cleared
- [x] The player should jump to the specific station. For that the route Index should be updated.
- [x] The chunks and the translation (big) chunk system should properly work with it.
- [x] The station table should be updated correctly

**Comment by bodamat** [comment]
Thanks for your advise! Could you please give some videos or photos to understand more clear?

**Comment by Jean28518** [comment]
That's a good advice, but with the scenario itself that could crash it.
Because, the trains, which you meet at the track, are timed very accurate. With this function that will be obsolete...
So honestly I don't know how to implement that usefully for us.

**Comment by Mrxx99** [comment]
![LibreTrainSimRestartJump](https://user-images.githubusercontent.com/33566379/108634497-0c87f180-747a-11eb-925d-ff6abb0a2e77.gif)
This is how I meant it.

So restarting should not be a problem. I basically have it working like shown in the gif, but it probably should also show the loading screen. If jumping causes problem with timing it could maybe also be done to set the time to the station you jump to from the schedule but that seems much harder to do.

**Comment by simfann** [comment]
Jump to stations is a good idea. I understood the problems caused by an implementation. But I have an idea for a solution of this problem together with a new proposal: Get also a map of the stations into the screen, where the driven train and other trains can be seen, like in OpenBVE. In OpenBVE it's also no problem to jump to stations. You see on the map, if there is another train at the jumped station.
![2021-02-22 19_46_52-openBVE](https://user-images.githubusercontent.com/79475795/108755337-6aced600-7547-11eb-9e26-fb8d7bceb186.jpg)

**Comment by Jean28518** [comment]
Thanks you both!

Of course a restart button shouldn't be the problem, and will get implemented to 0.8.

@simfann Good Idea, please open for the overview map a new issue.

> In OpenBVE it's also no problem to jump to stations. You see on the map, if there is another train at the jumped station.

You are right, but that doesn't work for our scenarios, because these have much more trains by default in a scenario ;) That jumping feature would crash every scenario, because the trains got spawned by time, and not when e.g. a player arrives at a station.. 
For testing there exists an debug option, with which you get very fast to other stations. But for real playing that won't work for us at the moment.

Maybe we get fixed this in the future.

**Comment by Jean28518** [comment]
> I basically have it working like shown in the gif, but it probably should also show the loading screen. If jumping causes problem with timing it could maybe also be done to set the time to the station you jump to from the schedule but that seems much harder to do.

That could work, but the player won't get the full scenario experience. Maybe we could just add a warning for that. Then the player could decide.. 

I will add this to an idea. I can't promise that we will get this feature to 0.8.

**Comment by simfann** [comment]
_That could work, but the player won't get the full scenario experience. Maybe we could just add a warning for that. Then the player could decide.._

I could live very well with the fact, that the player won't get the full scenario experience by jumping. A warning for that should be enough.

**Comment by Jean28518** [comment]
done
