### ISSUE TITLE
Crash of program while loading route U2-Nuremberg

### ISSUE THREAD

**Issue by simfann** [Libre-TrainSim/Libre-TrainSim#75]
With my PC it's not possible to start "U2-Nuremberg". With any configuration (route to or back, easy mode or not, both trains) "U2-Nuremberg" begins to load, but doesn't come to an end (more than 30 min) or crashes. "Wolfsfurt-Buchenhain" and all tutorials have no loading problems and work very fine. I tried to load "U2-Nuremberg" with program version v0.6, to which this route isn't officially assigned. This worked very fine, only some objects were not good, but I understand, that "U2-Nuremberg" was not written for v0.6. You can see the technical dates of my PC in attachment.
![2021-02-22 20_08_08-System](https://user-images.githubusercontent.com/79475795/108757332-fcd7de00-7549-11eb-9edf-ea67e03bdd50.jpg)

**Comment by simfann** [comment]
I just want to add more technical data of my pc in the attachment; perhaps this information can be helpful.
[ULI-LAPTOP technical dates.txt](https://github.com/Jean28518/Libre-TrainSim/files/6031057/ULI-LAPTOP.technical.dates.txt)

**Comment by Jean28518** [comment]
Mhm.. That's very weird.

Technically the tracks shouldn't differ to much. The only thing I can imagine, is that your RAM is to low, because U2 Nuremberg is the biggest project with many objects.

I already fixed that for the new version. The files shrinked a lot, and the loading time for the pc got very faster. 
But that's not implemented in 0.7 :(

Thanks for reporting!
Jean
